name: energy_demand
version: "1.0.0"
config-version: 2

profile: energy_demand

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - target
  - dbt_packages

models:
  energy_demand:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
