apiVersion: v1
kind: Secret
metadata:
  name: forecast-secrets
  namespace: energy-forecast
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "CHANGE_ME"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"
  S3_ENDPOINT_URL: "http://minio-service:9000"
  API_KEYS: "CHANGE_ME"
  ENTSOE_API_KEY: "CHANGE_ME"
